server:
  port: 8004

spring:
  application:
    name: spring-rabbitmq
  rabbitmq:
    host:
    port: 5672
    username:
    password:

#注册中心
eureka:
  instance:
    hostname: localhost
    # 是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #注册到Eureka的账号密码
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:8761/eureka/
#      defaultZone: http://localhost:8761/eureka/
